# docker-compose build
# docker-compose up
version: "3"
services:
  app:
    build:
      context: .
    image: "qualis-hugo"
    container_name: "qualis-hugo"
    restart: always
    ports:
      - "81:80"
